#!/bin/sh

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# Note: the "Mod4" modifier is also known as Logo, GUI, Windows, Mod4, etc.

# mouse follows cursor
riverctl focus-follows-cursor normal

riverctl map normal Mod4+Shift Return spawn alacritty
riverctl map normal Mod4 p spawn 'wofi --show drun'
riverctl map normal Mod4 Backspace spawn 'swaync-client -t -sw'
# toggle keyboard layout
riverctl map normal Mod4 Z spawn "$HOME/.config/river/toggle-keyboard.sh"

riverctl map normal Mod4+Shift p spawn firefox

# Mod4+Q to close the focused view
riverctl map normal Mod4 Q close

# # Mod4+Shift+E to exit river
riverctl map normal Mod4+Shift E exit

# Mod4+J and Mod4+K to focus the next/previous view in the layout stack
riverctl map normal Mod4 J focus-view next
riverctl map normal Mod4 K focus-view previous

# Mod4+Shift+J and Mod4+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Mod4+Shift J swap next
riverctl map normal Mod4+Shift K swap previous

# Mod4+Period and Mod4+Comma to focus the next/previous output
riverctl map normal Mod4 Period focus-output next
riverctl map normal Mod4 Comma focus-output previous

# Mod4+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Mod4+Shift Period send-to-output next
riverctl map normal Mod4+Shift Comma send-to-output previous

# Mod4+Return to bump the focused view to the top of the layout stack
riverctl map normal Mod4 Return zoom

# Mod4+H and Mod4+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Mod4 H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Mod4 L send-layout-cmd rivertile "main-ratio +0.05"

# Mod4+Shift+H and Mod4+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal Mod4+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Mod4+Shift L send-layout-cmd rivertile "main-count -1"

# Mod4+Mod1+{H,J,K,L} to move views
riverctl map normal Mod4+Mod1 H move left 100
riverctl map normal Mod4+Mod1 J move down 100
riverctl map normal Mod4+Mod1 K move up 100
riverctl map normal Mod4+Mod1 L move right 100

# Mod4+Mod1+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Mod4+Mod1+Control H snap left
riverctl map normal Mod4+Mod1+Control J snap down
riverctl map normal Mod4+Mod1+Control K snap up
riverctl map normal Mod4+Mod1+Control L snap right

# Mod4+Mod1+Shift+{H,J,K,L} to resize views
riverctl map normal Mod4+Mod1+Shift H resize horizontal -100
riverctl map normal Mod4+Mod1+Shift J resize vertical 100
riverctl map normal Mod4+Mod1+Shift K resize vertical -100
riverctl map normal Mod4+Mod1+Shift L resize horizontal 100

# Mod4 + Left Mouse Button to move views
riverctl map-pointer normal Mod4 BTN_LEFT move-view

# Mod4 + Right Mouse Button to resize views
riverctl map-pointer normal Mod4 BTN_RIGHT resize-view

# Mod4 + Middle Mouse Button to toggle float
riverctl map-pointer normal Mod4 BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Mod4+[1-9] to focus tag [0-8]
    riverctl map normal Mod4 $i set-focused-tags $tags

    riverctl map normal Mod4 Tab set-focused-tags $tags

    # Mod4+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Mod4+Shift $i set-view-tags $tags

    # Mod4+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Mod4+Control $i toggle-focused-tags $tags

    # Mod4+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Mod4+Shift+Control $i toggle-view-tags $tags
done

# Mod4+Tab to tab back and forth between tags
riverctl map normal Mod4 Tab focus-previous-tags

# Mod4+0 to focus all tags
# Mod4+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Mod4 0 set-focused-tags $all_tags
riverctl map normal Mod4+Shift 0 set-view-tags $all_tags

# Mod4+Space to toggle float
riverctl map normal Mod4 Space toggle-float

# Mod4+F to toggle fullscreen
riverctl map normal Mod4 F toggle-fullscreen

# Mod4+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Mod4 Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Mod4 Right send-layout-cmd rivertile "main-location right"
riverctl map normal Mod4 Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Mod4 Left  send-layout-cmd rivertile "main-location left"

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pactl set-sink-volume @DEFAULT_SINK@ +5%'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pactl set-sink-volume @DEFAULT_SINK@ -5%'
    riverctl map $mode None XF86AudioMute         spawn 'pactl set-sink-mute @DEFAULT_SINK@ toggle'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Screenshot
    riverctl map $mode None Print spawn 'grim - | wl-copy'

    # Control screen backlight brightness with light (https://github.com/haikarainen/light)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'light -A 10'
    riverctl map $mode None XF86MonBrightnessDown spawn 'light -U 10'
done

# Set background and border color
riverctl background-color 0xF5C2E7
riverctl border-width 5
riverctl border-color-focused 0xfff5c2e7
riverctl border-color-unfocused 0xff45475a

# Spawn new windows at the bottom of the stack
riverctl attach-mode bottom

# Set keyboard repeat rate
riverctl set-repeat 45 245

# Make certain views start floating
# riverctl float-filter-add app-id float
# riverctl float-filter-add title "popup title with spaces"

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 &

post_launch() {
	sleep 1;
	swww img $HOME/.config/river/wallpapers/clouds.png --transition-type random --transition-duration 1
	eww open main
}

post_launch &
exec runsvdir "$HOME/service"
