#!/usr/bin/env bash
wallpaper=$(find ~/.local/share/wallpapers -type f | shuf -n 1)
swww img $wallpaper --transition-type=wave --transition-duration 1 --transition-step=10 --transition-fps=144 --resize crop
wal -i $wallpaper -n


